SELECT * FROM customer_behaviour.customer_shopping_behavior;
select * from customer_behaviour.customer_shopping_behavior limit 20;

-- Q1. What is the total revenue generated by male vs. female customers?

SELECT Gender, 
       SUM(`Purchase_Amount_(USD)`) AS Revenue
FROM customer_behaviour.customer_shopping_behavior
GROUP BY Gender
LIMIT 0, 1000;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 

SELECT Customer_ID, `Purchase_Amount_(USD)`
FROM customer_behaviour.customer_shopping_behavior
WHERE Discount_Applied = 'Yes'
  AND `Purchase_Amount_(USD)` >= (
      SELECT AVG(`Purchase_Amount_(USD)`)
      FROM customer_behaviour.customer_shopping_behavior
  );
  
-- Q3. Which are the top 5 products with the highest average review rating?
  
SELECT Item_Purchased, 
       round(AVG(Review_Rating)) AS `Average Product Rating`
FROM customer_behaviour.customer_shopping_behavior
GROUP BY Item_Purchased
ORDER BY AVG(Review_Rating) DESC
LIMIT 5;
  
-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

SELECT Shipping_Type,
       ROUND(AVG(`Purchase_Amount_(USD)`), 2) AS Average_Purchase
FROM customer_behaviour.customer_shopping_behavior
WHERE Shipping_Type IN ('Standard', 'Express')
GROUP BY Shipping_Type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.

SELECT 
    Subscription_Status,
    COUNT(Customer_ID) AS Total_Customers,
    ROUND(AVG(`Purchase_Amount_(USD)`), 2) AS Avg_Spend,
    ROUND(SUM(`Purchase_Amount_(USD)`), 2) AS Total_Revenue
FROM customer_behaviour.customer_shopping_behavior
GROUP BY Subscription_Status
ORDER BY Total_Revenue DESC, Avg_Spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT 
    Item_Purchased,
    ROUND(SUM(CASE WHEN Discount_Applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS discount_rate
FROM customer_behaviour.customer_shopping_behavior
GROUP BY Item_Purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

WITH Customer_Type AS (
    SELECT 
        Customer_ID, 
        Previous_Purchases,
        CASE 
            WHEN Previous_Purchases = 1 THEN 'New'
            WHEN Previous_Purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS Customer_Segment
    FROM customer_behaviour.customer_shopping_behavior
)
SELECT 
    Customer_Segment, 
    COUNT(*) AS `Number of Customers`
FROM Customer_Type
GROUP BY Customer_Segment;

-- Q8. What are the top 3 most purchased products within each category? 
WITH Item_counts AS (
    SELECT 
        Category,
        Item_Purchased,
        COUNT(Customer_ID) AS Total_orders
    FROM customer_behaviour.customer_shopping_behavior
    GROUP BY Category, Item_Purchased
),
Ranked_Items AS (
    SELECT 
        Category,
        Item_Purchased,
        Total_orders,
        ROW_NUMBER() OVER (PARTITION BY Category ORDER BY Total_orders DESC) AS item_rank
    FROM Item_counts
)
SELECT 
    Category,
    Item_Purchased,
    Total_orders,
    item_rank
FROM Ranked_Items
WHERE item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

Select Subscription_Status,
count(Customer_ID) as repeat_buyers
 from customer_behaviour.customer_shopping_behavior
 where Previous_Purchases > 5
 group by Subscription_Status;

-- Q10. What is the revenue contribution of each age group? 

SELECT 
    Age,
    SUM(`Purchase_Amount_(USD)`) AS total_revenue
FROM customer_behaviour.customer_shopping_behavior
GROUP BY Age
ORDER BY total_revenue DESC;
